name: Integration tests
on: ['push']

jobs:
  build_and_copy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Cache node_modules
      uses: actions/cache@v1
      with:
        path: frontend/node_modules
        key: ${{ runner.OS }}-node_modules-${{ hashFiles('**/package-lock.json') }}
        restore-keys: ${{ runner.OS }}-node_modules

    - name: Install dependencies
      working-directory: frontend
      run: npm install

    - name: Build static frontend
      working-directory: frontend
      run: npm run export

    - name: Upload static frontend
      uses: actions/upload-artifact@v1
      with:
        name: frontend
        path: backend/static

  run_cypress:
    runs-on: ubuntu-latest
    needs: build_and_copy
    steps:
    - uses: actions/checkout@v1

    - name: Download compiled static frontend
      uses: actions/download-artifact@v1
      with:
        name: frontend
  