name: Backend Checks
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: check
    - uses: actions-rs/cargo@v1
      with:
        command: test
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions-rs/clippy-check@v1.0.5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
