name: Rust Checks
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Cache target directory
      uses: actions/cache@v1
      with:
        path: target
        key: ${{ runner.OS }}-target-${{ hashFiles('**/Cargo.*') }}
        restore-keys: ${{ runner.OS }}-target

    - name: Install dependencies
      run: sudo apt-get install libsqlite3-dev

    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true

    - name: Run cargo check
      uses: actions-rs/cargo@v1
      with:
        command: check

    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Cache target directory
      uses: actions/cache@v1
      with:
        path: target
        key: ${{ runner.OS }}-target-${{ hashFiles('**/Cargo.*') }}
        restore-keys: ${{ runner.OS }}-target
    
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true

    - name: Run clippy
      uses: actions-rs/clippy-check@v1.0.5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
